title: Minimal theme
logo: /assets/png-clipart-humanoid-robot-android-robot-electronics-photography-thumbnail.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
