title: Manish Tyagi
logo: /assets/png-clipart-humanoid-robot-android-robot-electronics-photography-thumbnail.png
description: I am a Financial analyst and a Data Scientist
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
